baseURL: 'https://bensutton.com'
title: 'Benjamin Sutton'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'
ignoreErrors: ["error-remote-getjson"]